sonar.projectKey=app-reservas
sonar.projectName=App Reservas
sonar.sourceEncoding=UTF-8

sonar.sources=auth-service/src,booking-service/src,user-service,notification-service,frontend/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/.next/**,**/package-lock.json,**/*.test.js,**/*.spec.js

sonar.tests=auth-service/src,booking-service/src
sonar.test.inclusions=**/*.test.js

sonar.javascript.lcov.reportPaths=auth-service/coverage/lcov.info,booking-service/coverage/lcov.info

sonar.qualitygate.wait=true
