sonar.projectKey=app-reservas
sonar.projectName=App Reservas
sonar.sourceEncoding=UTF-8

sonar.sources=auth-service/src,booking-service/src,user-service,notification-service,frontend/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/.next/**,**/package-lock.json

sonar.qualitygate.wait=true
